[splunktcp://9997]
disabled = 0
_TCP_ROUTING = splunk-target-group,non-splunk-target-group

[splunktcp-ssl://9997]
disabled = 0
_TCP_ROUTING = splunk-target-group,non-splunk-target-group

[SSL]
serverCert = /opt/splunk/etc/auth/server.pem
sslPassword = $7$l/TxoDAGo8OJOXkRAg1jeM7EaJMIW/XsLYJRIMbHx0s5DBGi2fMjrHtE+18=


[tcp://1515]
disabled = 0

[udp://1515]
disabled = 0
no_appending_timestamp = true
no_priority_stripping = true

[udp://5514]
disabled = 0 
index = checkpoint
sourcetype = checkpoint
