[tcpout]
defaultGroup = splunk-target-group
persistentQueueSize = 500MB
queueSize = 500MB

[tcpout:splunk-target-group]
server = 10.94.67.2:9997,10.94.67.21:9997,10.94.67.22:9997
compressed = false
disabled = 0
autoLBFrequency=10


#in case of sending udp to two differnt siem server which one is not splunuk
#need to change in transforms to _syslog_routing

[syslog:non_splunk_group_1]
server = 10.94.67.28:514
sendCookedData = false
type=udp
#syslogSourceType = sourcetype::system

#[syslog:non_splunk_group_2]
#server = 10.0.0.2:514
#sendCookedData = false
#type=udp
#syslogSourceType = sourcetype::system2


#in case of sending tcp to two differnt siem server which one is not splunuk
#need to change in transforms to _tcp_routing
#[tcpout:non_splunk_group]
#server = 10.94.67.28:514
#sendCookedData = false
#defaultGroup=non_splunk_group




