[credential:postgres:oas.dbuser:]
password = $7$vM2mJQpU6w7QN7DMxqlx5WX+Tn45mE8dUOWmQ4Iy7UFY/6Mh+8jCvAxDhV7Qefo4uvW1ChbGxOPJHj5/ZuxO9Q==

[credential:postgres:oas.root:]
password = $7$350mx5evUtDD/mBl7u7uk4Zdjk3RgOwYz1qn9Y8bGkuKhGXSM80I1g4dfgis5lnsqsFijpv5kBz8q7J6vSSEcQ==

[credential:postgres:do.root:]
password = $7$uj0btICwytVENFBc7ADrgg0p/0BiK2zVDflRLLv3yqHUFsUOJnUAt1A9DwR2CK6a2OKj6O3GY32fnxMFpLAJrg==

[credential:postgres:do.dbuser:]
password = $7$2te2w2Or2+zxy6H216FcsspoTLRm/kdfs2pNJQRK0YC5F90LfxkNQ9p1rWpwDHAF/GH0CucbbX5JL3cAhW+eag==

[credential:postgres:kvstore.pdl:]
password = $7$zkfC5Kn6+QRxiJOa2sIbm2sHZuiOq+puxMc2FhroGLm9cj5oHZUlx3bDWhp3gaDmW2+ZI0xoRfGr0dwUOLShZg==

[credential:postgres:acc.dbuser:]
password = $7$iQVIPd1mvBhmXUfhPIU4Cp3F8ePE5v0kRlqvynw1A1j5/mybo7Cn42JR3jRqxjey9DmEFUHz7sJBrLZVwYWwOQ==

[credential:postgres:deployment_guid:]
password = $7$Np4rC7kHFs8WV20sYsUl3+qDZ+1VRgh8LFY+aQFX0AG29d9lnUibXzhKV7LYMPr7qvegSFihvSC/bJgbAPYiXRtJaql5ke0BSS6WTEprTg==

[credential:postgres:postgres_admin:]
password = $7$NTXkqBoKTh/qTkzQARfLurBR+3x53MIo6VAyvreTlwMQKWaEGKfJ8N8njqZgx7Mck248HLOSexwiw6zmjx6EOA==
