#in case of sending the same data to another siem which is not splunk
[checkpoint]
TRANSFORMS-route = route_to_non_splunk
[checkpoint]
SEDCMD-strip_double_header_checkpoint = s/^\w\w\w\s\d+\s\d+\D\d+\D\d+\s\d+\D\d+\D\d+\D\d+\s//g

#split windows wef to windows and sysmon indexes
[XmlWinEventLog:ForwardedEvents]
TRANSFORMS-routing_indexes_wef = route_sysmon_from_wef

