#in case of sedning to another siem which is not splunk.
#need to use _SYSLOG_ROUTING for udp and _TCP_ROUTING for tcp
[route_to_non_splunk]
REGEX = .
DEST_KEY = _SYSLOG_ROUTING
FORMAT = non_splunk_group_1,non_splunk_group_2

#for splitting wef to windows and to sysmon seperate indexes
[route_sysmon_from_wef]
REGEX = (?m)<Channel>Microsoft-Windows-Sysmon\/Operational<\/Channel>
DEST_KEY = _MetaData:Index
FORMAT = dev_sysmon
