#in case of sedning to another siem which is not splunk.
#need to use _SYSLOG_ROUTING for udp and _TCP_ROUTING for tcp
[route_to_non_splunk]
REGEX = .
DEST_KEY = _SYSLOG_ROUTING
FORMAT = splunk-target-group,non_splunk_group