[credential:postgres:do.root:]
password = $7$LzhXk8Qh7k0Vg1O/ndE7UhKr61nM0p4MGRLTntV/0erhjHt7rnWmvbCvsQJc49xVmUMH7nJclmho4jAklkTdmg==

[credential:postgres:do.dbuser:]
password = $7$TndGGHoz+x0jRF3BUntu21ywJtP6jdOGVJFAmtw/XH5HRWMvYUlTMgAAhtbtvwb8wG8QaiSf5Pcakys90KwMXQ==

[credential:postgres:kvstore.pdl:]
password = $7$mK0rkLHjNyuEpiTb32z0MQShfqlSFrHSWtxSbyNLu8BQTh4JwnHdycQblBO0b87OkEAWZJV6QzHFqyrY0GOt8g==

[credential:postgres:acc.dbuser:]
password = $7$bKaw7q/MxcvXmf9XtUO9boRCIfraYGRmV0xiGR101YTIjeXxjhbXorAwc7cjec0mpAoEjy94khd8ZmbT4Igi9w==

[credential:postgres:oas.root:]
password = $7$ZJaY9SJmOjqkksI71zstfydq4xnBcaTU9iM8aPq5QKUiyb+gvvbZ8NFSl+s/WR2fsZhiO4IEmNAgk2y9V/1kCw==

[credential:postgres:oas.dbuser:]
password = $7$dVWJUwdPYWVWce7CdhE/dBdYvmZs5r9vnGh34O+WTrWbfITIGDqRL0huH9btAzvV2dEMD8Jy7fXHucsM1dFZwQ==

[credential:postgres:deployment_guid:]
password = $7$aUQGD4CiN8V0JkgPymtq2E6HjWRDHUNljk2TlyEvn1ZY00X+/uY7NPPU9K4TF7Jc7J++2Xl2rSoXBL2YLvE/w9gTIhECaPRcPUnsVJ+S6g==

[credential:postgres:postgres_admin:]
password = $7$iBZTUXq1WtRT0dFSJV5iktQ7Cy9I7NrCIz7TYTPKAXQEIX9C32pgEcXR37gIEs+LXFYCkceeHBOt5V7spme4cg==
