[general]
serverName = indexer3
pass4SymmKey = $7$vh8NbCeL+Mm/jArzQbRZqxTbqHoD9k9/muPjN6Xes5VDATgfYnhcjQ==
site = site3
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[sslConfig]
sslPassword = $7$9GUN3A2u6kSwo5b0D6pV1vOScoSFqelxLZMjR3YqLYb8No/5SqfPvw==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[replication_port://9201]

[clustering]
manager_uri = https://10.94.67.20:8089
mode = peer
pass4SymmKey = $7$uFlBoKxpQWcn0Vgim2lpRs3ysQnxJvJwzkXwmLVtK4lihHL53QGTTbs0Iww=
cluster_label = idxcluster

[kvstore]
disabled=true

