[general]
serverName = sh3
pass4SymmKey = $7$fc83W1cuhjb6TKQK5o6+s2RRA4vTS4ABgjxXdMlCPpycKgpHEhAcqw==
site = site3

[sslConfig]
sslPassword = $7$g0q6qxJzGE6GsUHs9WxF7X2U8QTK2g6lKJtegOmP4hy7MHD56QLavw==
[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[replication_port://9200]

[shclustering]
conf_deploy_fetch_url = https://10.94.67.19:8089
disabled = 0
mgmt_uri = https://10.94.67.18:8089
pass4SymmKey = $7$fFnTQYBHe93vr/4CrG0RjCTWgXrdQRTPt8eu1KtzBtLYnGYjyZrW0+lStTg=
shcluster_label = shc_a
id = 1D53AB32-456D-4E46-8FAF-CF55B449052E

[raft_statemachine]
disabled = false
replicate_search_peers = true

[clustering]
manager_uri = https://10.94.67.20:8089
mode = searchhead
pass4SymmKey = $7$oXp8KZB4YioGq5Z34p6uC8teDy6NC8NgtxHGcKKq3BzUM/X5epd0NakOl1k=
multisite = true
cluster_label = idxcluster
