[WinEventLog://Application]
disabled = 0
#start_from = oldest
#current_only = 0
checkpointInterval = 5
renderXml=true
index = windows
persistentQueueSize = 500MB
current_only = 1
queueSize = 500MB

[WinEventLog://Security]
disabled = 0
#start_from = oldest
#current_only = 0
evt_resolve_ad_obj = 1
checkpointInterval = 5
blacklist1 = EventCode="4662" Message="Object Type:(?!\s*groupPolicyContainer)"
blacklist2 = EventCode="566" Message="Object Type:(?!\s*groupPolicyContainer)"
#blacklist3 = $XmlRegex=%<EventID>4688</EventID>.+["']NewProcessName["']>C:\\Program Files \(x86\)\\Microsoft\\Edge\\Application\\msedge\.exe.+["']ParentProcessName["']>C:\\Program Files \>
#blacklist4 = $XmlRegex=%<EventID>(4688|4672)</EventID>%
renderXml=true
index = windows
persistentQueueSize = 500MB
current_only = 1
queueSize = 500MB

[WinEventLog://System]
disabled = 0
#start_from = oldest
#current_only = 0
checkpointInterval = 5
renderXml=true
index = windows
[WinEventLog://Microsoft-Windows-PrintService/Operational]
disabled = 1
start_from = oldest
current_only = 0
checkpointInterval = 5
persistentQueueSize = 500MB
current_only = 1
queueSize = 500MB

###### Forwarded WinEventLogs (WEF) ######
[WinEventLog://ForwardedEvents]
disabled = 0
#start_from = oldest
checkpointInterval = 5
## The addon supports only XML format for the collection of WinEventLogs using WEF, hence do not change the below renderXml parameter to false.
renderXml=true
host=WinEventLogForwardHost
persistentQueueSize = 500MB
current_only = 1
queueSize = 500MB

#test for recieving syslog from uf and send to multiple siems and not just splunk
[udp://5514]
sourcetype = cp_log
no_appending_timestamp = true
