[credential:postgres:oas.dbuser:]
password = $7$NbeOi6ETiE8GDGdv7hjjxtwaoz/6EG8K5r8ncQetbkIjasRyQgOGOtGNsQF04mWXqfOxYEJ3IQhHwaEsxvP3FQ==

[credential:postgres:oas.root:]
password = $7$EB68FbRQb4cKWKiEpMhPg1jEd0RUfZStIzYAvooIqZTIY5HNpaCYtT/FnzcTdcF1r6xlr4QgkfKJE25eM5j72Q==

[credential:postgres:do.root:]
password = $7$I370fVfpFunSY5Oslx4aPz3bsEeO+izA+7pyVzkjbwMSBlr4UUVuYAp3k/q4/HLCtZ52vcVsipHpmzW8EuxDOg==

[credential:postgres:do.dbuser:]
password = $7$L5Q/S8A3rfWS20YwC2t094sK80mBG6Q4qU5Y3n9Z80LT20xHzPxlauaQPSjMUCYJQ/XXTdc6ETvLePZK9QXMlw==

[credential:postgres:kvstore.pdl:]
password = $7$DnCg8e3h1OIb0A5RKBTwq4PomlH8a7AdMkKnPeANwNlehJYiDVUDnDLV2+0+4tCcsFJjQCEhVIaX5uoDOs4fZw==

[credential:postgres:acc.dbuser:]
password = $7$8jXGIHuil3N35ErPPcX6Qv5xkvAd51lCfKKj7sY2V7tI1enjEGhKoz7fc84cdWVFGVmIBx+JRF3TXZLyUJNbTQ==

[credential:postgres:deployment_guid:]
password = $7$SUw4FxGXGFyG1W31m1/nlOnIg5LyZxwLbSPvQzmEgCpgA+hISqn+P1dvw/Nk8mej5q65VKZ46uLYhHjjQ6NpvWsaLiTcGhgMWRAoyWifgQ==

[credential:postgres:postgres_admin:]
password = $7$7haTh1/HVDEggzrQucxc1w28j3+xFVY+22oFLTCiXxXbe85mnzviHpwb/8R9GpzWVqEgUFtJv7kBjx/5gTv5ng==
