[general]
serverName = cluster-manager
pass4SymmKey = $7$g7PtS3Fj3+UDDZTBK7y2+JlMrUhNlxT6pzIVC2GARWEepLmLx4HgBg==
site = site1
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[sslConfig]
sslPassword = $7$HkVoEmIHCCvJ6BWjR7Dbv+KwUYgGX+eRL1vQF1imVpwjoRxmCXTZHQ==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[clustering]
cluster_label = idxcluster
mode = manager
pass4SymmKey = $7$GiWJop5XlY3YpGO/xcJc1O96sKC7V6Y/r1/LB/QaVlU6vCWybvIO4VZp2o0=
multisite = true
available_sites = site1,site2,site3
site_replication_factor = origin:1, site1:1, site2:1, site3:1, total:3
site_search_factor = origin:1, site1:1, site2:1, site3:1, total:3
rebalance_threshold = 0.9

[kvstore]
disabled=true
