[credential:postgres:do.dbuser:]
password = $7$e4fFnNL3q7vNESIPJXHeKOPG2AXQlJN+uSvO6jmPrpwQjm9QeFNIMzibqy1S70c9uj3MLpxywkZvt2uorCQ4vg==

[credential:postgres:do.root:]
password = $7$dkd1lu/9gHE9zp2ann2OCWkfsU7828kM6YWBtDP3o4KXabW6APwuDq8mj0+OD9NJnrttQrFiBmeYlQP6sY6hGw==

[credential:postgres:kvstore.pdl:]
password = $7$T11TtKGQsvBufR+Afg720Z8HkOLi2NlpdSwOfL+71B/E8S4Fdjo86thVPb9qbqxFGIRQeGdETN1G4rrONbEHpw==

[credential:postgres:acc.dbuser:]
password = $7$nf++hgToNSGHnsDwR52dmr6dsZE49+LEHFkGfVPlafOE9p8JHP4IdqAUAbJwb6XN+B4J0Shw3FY6mc7kW+cQiQ==

[credential:postgres:oas.root:]
password = $7$khzrxnX5EwrBqj+LOyETeb5IZjbqONaFDKcdasgJFy4//0OgfKm44rzBzGclwmGbwj4QjNjOqiIoDsXaymoKTw==

[credential:postgres:oas.dbuser:]
password = $7$/dTSJM7PiXKoXdHN9rfamQ2PxGoeel5DkZ9deS+LuKC5wpTjV7SQRxOVqZ8BiC9WdhNjgC+Rcsy7cOao8Krwog==

[credential:postgres:deployment_guid:]
password = $7$IMpnl5UotN1QEsnYyu4db8BEluGA9owgKQUdB/6J+RdrvK0xfrIfuwYiEIuSaclgiN7A9E4Od5NBg6JqYwEYNGMcuG3bd4WhQGUQ1yuiEg==

[credential:postgres:postgres_admin:]
password = $7$/fj5rll1rzIocSetUWfTIIhI8qVfoZuFWlZR2We80RmjuDc4Q8IHQlCWPL4SSAnRFLBaq2nMt+J9nKtPgEREnA==
