[tcpout]
defaultGroup = heavy_forwarder_target
forwardedindex.2.whitelist = (_audit|_internal|_introspection|_telemetry|_metrics|_metrics_rollup|_configtracker|_dsclient|_dsphonehome|_dsappevent)
[tcpout:heavy_forwarder_target]
server = 10.94.67.4:9997
compressed = false

[indexAndForward]
index = true 
selectiveIndexing = true
