[general]
serverName = ds
pass4SymmKey = $7$DAa/CvxfQepqpbcGJJzOz/PYC2QXInFprGJFDx2fp6h+FE1yG2aidg==

[sslConfig]
sslPassword = $7$TGYT5zHnXHq42rd/V6v32ZrxyVXmfesbIsJQhtUAFRJpSYqhgMG3OA==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089
