[credential:postgres:oas.dbuser:]
password = $7$1UfZf2ULZ4oP5OuLC0Z3PBIvOh+BqKlp+OQdmwoATSUbN2mWNVz0QXmukRrkP9JFifR/fuwEL/YjXGkxKsJS3A==

[credential:postgres:oas.root:]
password = $7$BeOmNCgdhVOAFMqUbs1S3MgcXt0ivfJNW1pApfgBqDmfqUL89GgR1z9ON/ENUpBHZ9tgWMe4AkVkrczFNRvGvA==

[credential:postgres:do.root:]
password = $7$Cl/Oa1/twJNi90TX4BZBjSmhR/rL3AaRzXlqjhyCVSwfuwMP6VTdfGpdrbrtXoxFS6jHO0y6TyT4fZsyzxihTQ==

[credential:postgres:do.dbuser:]
password = $7$NO+dOyUJabtzejJMt+EGjDFkDuXkWcTkW9aXM7Clis0p1gqhwzi8HVZV+D8i/ByJCdx7TmE/ed2J2Ycxj9PMcQ==

[credential:postgres:kvstore.pdl:]
password = $7$CQmp68YAJk56R1c0EiTrcD5U7d6f1fhg0ILd8TPeyBsNwmc/tinnvqg3leCBqXnloHUXbeuaySzElOgLqe/2wQ==

[credential:postgres:acc.dbuser:]
password = $7$qe5Z1R7qi4YRYe/0AJFTsHtaNfA8F0AOi0fKWa+lng7QH0tbtdR4niV1zrNDoVRpQys2AI43yeD+kkX994ky6Q==

[credential:postgres:deployment_guid:]
password = $7$k3tTpq+RLyVNp64bF5naf6bMac78RKQLDvYkhGr7f+r92EQNY7XP7D593Kt9/8EBtD4DdShEGb70JkYP/nKnJwAB4Q7h1E2ynymsh7V+0Q==

[credential:postgres:postgres_admin:]
password = $7$iWY+dX643QMy18/T3Vd57p6k0qmsrzrhbLzejcT9oTgYJN7OwVCYSPa+UuRAwT3Hi0h4qDN7J6ZLd8+13VO31g==
