[general]
serverName = indexer2
pass4SymmKey = $7$+yUQDbl/V6DK74WO6GG2gNyglhD30iA5sc4etxZBVhf8IEvuOBQVBQ==
site = site2
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[sslConfig]
sslPassword = $7$hrjQNq6uduMiBMpJi/XUjYflfPkl9TmupE3XLfu0z97IqV8bN6NFLw==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[replication_port://9201]

[clustering]
manager_uri = https://10.94.67.20:8089
mode = peer
pass4SymmKey = $7$VZYaUQHS+G5fZQzJFwU3Rh2wXOshwUoQi5fUfzADOyutfqn7uHd/60ygta8=
cluster_label = idxcluster

[kvstore]
disabled=true

