[credential:postgres:do.root:]
password = $7$2jtMNV1TLPngbcVUlcR8BzNHb6yyYrJw4Me9gmgv9aTDe4FzKgh/T2ranjGfUcOKXok0QqyQ/FgMIIGRX3O5gQ==

[credential:postgres:do.dbuser:]
password = $7$31W/CTyjE/06+IPn5cwLCAgX3GoN3e6cxIeYn+UrIJAW81u5pKAcW9hTCdRUMY1GPehnZEiitGjldTz6zhmoVQ==

[credential:postgres:kvstore.pdl:]
password = $7$yrr5Ee6ABVJaNLMh13y0oryvT36Q0cODy2182oSuVrAPPry3U6+UG7V3cBbtFrcFBi8H8BhLn+YaORCr2K6YzA==

[credential:postgres:acc.dbuser:]
password = $7$6zgAGOJQVWxAuYeyr0vaNqCFOKQV6IUx3jUw/FTo6XGUdLPrrsiIjkH7HXAkymxuj9ypIOBKmtWlGgP6v+jOPg==

[credential:postgres:oas.root:]
password = $7$qRPagPii5e9cn6fl4QdppOTr1SAXEDAHNYex7apmzT1GXqCu+Ze6AAOQJ8vdnPjZsEXmP3C4/4CkM+II9GWeKw==

[credential:postgres:oas.dbuser:]
password = $7$kb7GcEOhebPtV3P3dWzZfHTyizw61xQs277PlgYm6fApMw6CtTuGXsLRWW7LFXVFQ2hgEKNvO/kt/TnZNmY50A==

[credential:postgres:deployment_guid:]
password = $7$VA1zm2ENewfwhe9oANV3g1gSoF6gJWUJ/O7JAIPO1IkJH3A+4jgkyd1uIzsnqJnWVOlkAG2cEQzySG8zJgl27QexQMISzQpQIM/pxdIimg==

[credential:postgres:postgres_admin:]
password = $7$aa7YhEPZF7mE8lfryaj/5zmwTXmghOcKh9MQhEUONryyRHVueFEcD49yFi6p5Ag5ODCSbVvZuWQYanLqgquMpw==
