[general]
serverName = deployer
pass4SymmKey = $7$ljBWHaTrxyLYd1Y3mJ2sEByDtg5EhxP1bB11ooIthcYR27HtEAgstw==
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[sslConfig]
sslPassword = $7$lN/cHXNw7GdV8fozCJyRts06RKLRHvoyEdMwGrDoziGDKIw5fCoUHg==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[shclustering]
pass4SymmKey = $7$jGiWQUWjktp5FaFl0kEyKXwc15mWsCYpnuiRHa0kZ+wEm+1jkiydQ/wO7QA=
shcluster_label = shc_a

[httpServer]
max_content_length = 5000000000
