block parser win-parser() {
    channel {
        rewrite {
            r_set_splunk_dest_default(
                index("windows_sc4s")
                sourcetype("WinEventLog")
                vendor("Microsoft Windows")
                product("Windows")
                template("t_msg_only")
		source("WinEventLog")
            );
        };
        rewrite {
            set("$MSGONLY", value("MSG"));
        };
    };
};

application win-p[sc4s-syslog] {
    filter {
        message("MSWinEventLog");
    };
    parser { win-parser(); };
};





