[rewrite_source_wineventlog]
SOURCE_KEY = _raw
DEST_KEY = MetaData:Source
REGEX = MSWinEventLog\t\d*\t(\S+)\s
FORMAT = source::WinEventLog:$1
WRITE_META = true

#[rewrite_sourcetype_wineventlog]
#SOURCE_KEY = _raw
#DEST_KEY = MetaData:Sourcetype
#REGEX = MSWinEventLog\t\d*\t(\S+)\s
#FORMAT = sourcetype::WinEventLog:$1
#WRITE_META = true
