[role_ess_analyst]
ea_edit_table_fields = disabled
ea_save_filters = disabled
importRoles = ess_user;power;user
list_search_head_clustering = disabled
mc_assets_read = disabled
mc_health_report = disabled
mc_identity_read = disabled
mc_incident_sla_settings_read = disabled
mc_investigation_read = disabled
mc_response_template_view = disabled
mc_risk_score_read = disabled
mc_view_im_data = disabled
srchIndexesAllowed = ea_analytics;ea_discovery
srchMaxTime = 8640000
srchTimeEarliest = -1
srchTimeWin = -1
ueba_connections_read = disabled
ueba_detection_metadata_read = disabled
ueba_entitylist_edit = disabled
ueba_entitylist_read = disabled
ueba_ers_execution_post = disabled
ueba_finding_exclusion_edit = disabled
ueba_finding_exclusion_read = disabled
ueba_investigations_post = disabled
use_xproxyapi = disabled
