[splunktcp://9997]
disabled = 0
_TCP_ROUTING = splunk-target-group,non-splunk-target-group



[tcp://1515]
disabled = 0

[udp://1515]
disabled=0
no_appending_timestamp = true
no_priority_stripping = true
