[tcpout]
defaultGroup = splunk-target-group

[tcpout:splunk-target-group]
server = 10.94.67.2:9997,10.94.67.21:9997,10.94.67.22:9997
compressed = false
disabled = 0

#[tcpout-server://10.97.67.2:9997]
#[tcpout-server://10.97.67.21:9997]
#[tcpout-server://10.97.67.22:9997]

#[tcpout:non-splunk-target-group]
#server = :1515
#sendCookedData = false

#[syslog]
#defaultGroup = syslogGroup


#[syslog:syslogGRoup]
#server = :1515
#disabled = 0
#type = tcp

