[credential:postgres:do.root:]
password = $7$NLbQPZuc2rMkQp8pE7FPKf3t9o9ootwzkZg6OEo7k54TLREZ25ezLt/oPIbYwoRTAnH+yNCsqBRxwtS7xDw6PQ==

[credential:postgres:do.dbuser:]
password = $7$hj7XDalEW/tRLRiY3H3RXdGibpuU83ChyIglqHer/icdajoWqCl131EK3A2rCeSzkeYYv5PWLJyX/X7+i7H+4g==

[credential:postgres:kvstore.pdl:]
password = $7$APgUivnW0qjA5WJqKr2OtX/q249f5SMFId5/s42FJMRh+IQwl1IgbNVlUgZiOWBd+kdXKqlw/cvfNhXpjR1HVA==

[credential:postgres:acc.dbuser:]
password = $7$96pdgzoLVOQIN7FZHXYt8b49mBoNFCxx7HqmXg+ZRJp7zcsYRzjGVEarEg/S6hUJAByU3Cp5bdhZD7eYVILeMg==

[credential:postgres:oas.root:]
password = $7$6Pu847hksyypCDAhj1DAQTgnkjmJarKYRjhHiapjMM5wcfXXkC292Nvi21oTFFQ4tENcYYyPX1ILu1fQ3vdXlQ==

[credential:postgres:oas.dbuser:]
password = $7$wA63pmKzoSZ5uj6AllFmjqXWVTp8iHEk9NghBQFryLiAzZJvVLQSWJ1i4AVcwOfh7Tuh8ZFnBvQ/CaDxzPsztw==

[credential:postgres:deployment_guid:]
password = $7$ev8Ayvgr4YW0rD/fmNwzuHXPF9VTF75NvMvaHURhKDwAFtRBDRgjn88jzjG6GEogMxe2IzxaQaapwCRJG9XcMCnMFfgXP52QILL15Noh+w==

[credential:postgres:postgres_admin:]
password = $7$NsXvN2k2xD4crCiV34CC9W0zERhT08WovQhXJckwbSz0dAT94nQ0u7WbsM9efuO/0yLeNUWojzpwArUz7NFl6Q==
