[general]
serverName = indexer
pass4SymmKey = $7$F7ejFXbwegjHW/gW/S+2PT/gkVNKPMz6ne9PpLWqQ87ppTr9OIVJbg==
site = site1
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[sslConfig]
sslPassword = $7$1Ej36ycLyFp4DSBZrUIO0Ne5d9ys9hcNDLwDbxunJj765V3sNrkePQ==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
manager_uri = https://10.94.67.6:8089

[replication_port://9201]

[clustering]
manager_uri = https://10.94.67.20:8089
mode = peer
pass4SymmKey = $7$5g5xyEwrZZdqSB9Bj847fV6hUMDUL2Xjfz5XeZD6nLzQMm+u9MhwewVGX74=
cluster_label = idxcluster
