[credential:postgres:acc.dbuser:]
password = $7$1jEO+YaRYcubaCJZhsRpxTKEzs4wVHboHFWJZTEoc+14VcrGX6wKMklBPO8DyU7R4SpLf0w/wpQhTbcreQDROA==

[credential:postgres:oas.root:]
password = $7$AOGbUQf+m364i/cOfu/1FbcuQP1jmHEP67dtSfp2UroeLjg3ur5PDVCQWCPpQo0Qj1WLVHGeHFkVjja8T0UcYg==

[credential:postgres:oas.dbuser:]
password = $7$5EHsAOw9wS+ZNEXFtt76ZDeCxIzOBjntHzDK6hCRSYWs0wwmRRD4VOaLM0Q5uOmym0CjaJKwf27mO0kMruPmHQ==

[credential:postgres:do.root:]
password = $7$1F1+QyvYV6bgTxNphsMThP5tTkfSlBEQ0Ug9po4s8ALuzyIpfaUrwgZUTQr+eoj0TNvWZomK/8p7uPSVaOtElg==

[credential:postgres:do.dbuser:]
password = $7$Y9CmGv7Tt3xnM2cYG7oHVLauGfYu3eK+WmPmeZxHM5wphO/6EKZRg/ROjWFDsbTunmKuVFOVBxlDIfgxw/L/5Q==

[credential:postgres:kvstore.pdl:]
password = $7$vQ/5aGlnuGA3xknTF85C4qkXMfPZqkkTbX+wY/xC5FC92mvz1esFMTWfFBBQ7DAVjNskhNBphBGrQtyjLdAIbg==

[credential:postgres:deployment_guid:]
password = $7$gpIBBN21Y18FnVIXv/jVZUxQkB3mGBYfB7S6ui1abrBoF6vy7yUfnPBYpPmsvRILHFtyLWWXfCbLw3rKOujcpj0sUWRGWeOO8Gk/U7l4tQ==

[credential:postgres:postgres_admin:]
password = $7$qAcma0TntdFA+fnlEQ/zT5gwWKTAOTZmJFSyBapnnyfOUEm5tzkckUXGEY46tM+ZM7ZzCZd+NRAaaVohx2gwnA==
