[serverClass:linux:app:Splunk_TA_nix]
restartSplunkd = true

[serverClass:linux:app:outputs_uf]
restartSplunkd = true

[serverClass:windows:app:Splunk_TA_windows]
restartSplunkd = true

[serverClass:windows:app:outputs_uf]
restartSplunkd = true

[serverClass:linux]
machineTypesFilter = linux-x86_64
whitelist.0 = *

[serverClass:windows]
machineTypesFilter = windows-x64
whitelist.0 = *

[serverClass:linux:app:splunk_inputs_linux]
restartSplunkd = false
stateOnClient = enabled

[serverClass:windows:app:splunk_inputs_win]
restartSplunkd = false
stateOnClient = enabled
